-- TABLESPACE FOR ODATA4 TESTS
DROP TABLESPACE "odata_test" INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE "odata_test" LOGGING BLOCKSIZE 8192 DATAFILE  'odata_test_file.DBF'
SIZE 104857600 REUSE EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;

-- USER SQL
DROP USER odata_test CASCADE;

CREATE USER odata_test IDENTIFIED BY odata_test
DEFAULT TABLESPACE "odata_test"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON "odata_test";
-- If user creation fails:
--alter session set "_ORACLE_SCRIPT"=true;

GRANT CREATE SESSION TO odata_test;
GRANT CREATE SESSION TO odata_test;
GRANT CREATE TABLE TO odata_test;
GRANT CREATE ANY PROCEDURE TO odata_test;
GRANT CREATE SYNONYM TO odata_test;
GRANT CREATE VIEW TO odata_test;
GRANT create any trigger TO odata_test;
GRANT create sequence TO odata_test;
GRANT CONNECT,RESOURCE TO odata_test;

-- TYPES
CREATE TYPE ODATA_TEST.PHONE_ARRAY IS VARRAY (10) OF varchar2(30);
CREATE TYPE ODATA_TEST.TYPE7_STRUCT AS object (
    name VARCHAR2(19 BYTE),
    salary NUMBER,
    intervalYM  INTERVAL YEAR TO MONTH,
    intervalDS  INTERVAL DAY TO SECOND,
    timestampcontz TIMESTAMP WITH TIME ZONE ,
    datedate DATE,
    timestamptimestamp TIMESTAMP
);
CREATE TYPE ODATA_TEST.TYPE_STRUCT AS object (name VARCHAR2(19 BYTE), salary NUMBER);


-- TABLES

--
--DATETEST
--
CREATE TABLE ODATA_TEST.DATETEST (
    NAME VARCHAR2(40),
    STARTDATE TIMESTAMP
);

INSERT INTO ODATA_TEST.DATETEST (NAME,STARTDATE) VALUES ('name1',TIMESTAMP '2014-12-18 18:00:44.000000');
INSERT INTO ODATA_TEST.DATETEST (NAME,STARTDATE) VALUES ('name2',TIMESTAMP '2014-12-20 18:00:44.000000');
INSERT INTO ODATA_TEST.DATETEST (NAME,STARTDATE) VALUES ('name3',TIMESTAMP '2014-12-18 18:00:44.000000');

--
--INTERVALTEST
--
CREATE TABLE ODATA_TEST.INTERVALTEST (
    INTERVALYM INTERVAL YEAR TO MONTH,
    INTERVALDS INTERVAL DAY TO SECOND
);

insert into ODATA_TEST.INTERVALTEST values (TO_YMINTERVAL('-2-3'), TO_DSINTERVAL('1 21:01:02.345'));
insert into ODATA_TEST.INTERVALTEST values (TO_YMINTERVAL('15-7'), TO_DSINTERVAL('-0 01:02:03.333'));
insert into ODATA_TEST.INTERVALTEST values (TO_YMINTERVAL('10-10'), TO_DSINTERVAL('0 12:00:00'));

--
--PHONE_ARRAY_TABLE
--
CREATE TABLE ODATA_TEST.PHONE_ARRAY_TABLE (
    NAME VARCHAR2(20),
    PHONE_NUMBERS ODATA_TEST.PHONE_ARRAY
);

INSERT INTO ODATA_TEST.PHONE_ARRAY_TABLE (NAME,PHONE_NUMBERS) VALUES ('Smith', ODATA_TEST.PHONE_ARRAY('666-987-8549','555-125-7841'));

--
--STRUCT7_TABLE
--
CREATE TABLE ODATA_TEST.STRUCT7_TABLE (
    "id" NUMBER(22,0),
    EMPLOYEE7 ODATA_TEST.TYPE7_STRUCT
);

INSERT INTO ODATA_TEST.struct7_table VALUES (1, ODATA_TEST.type7_struct('John Smith', 20090.28, TO_YMINTERVAL('-2-3'), TO_DSINTERVAL('1 21:01:02.345'),
    TIMESTAMP '2017-01-21 21:05:53.46 +02:00', TO_DATE('21/01/2017','DD/MM/YYYY'), TIMESTAMP '1997-01-31 09:26:50.12'));

INSERT INTO ODATA_TEST.struct7_table VALUES (2, ODATA_TEST.type7_struct('Diane O''Donnell',32330.04, TO_YMINTERVAL('15-7'), TO_DSINTERVAL('-0 01:02:03.333'),
    TIMESTAMP '2017-01-21 21:05:53.46 +02:00', TO_DATE('21/01/2017','DD/MM/YYYY'), TIMESTAMP '1997-01-31 09:26:50.12'));

--
-- STRUCT_TABLE
--

CREATE TABLE ODATA_TEST.STRUCT_TABLE (
    ID VARCHAR2(4),
    EMPLOYEE ODATA_TEST.TYPE_STRUCT
);

INSERT INTO ODATA_TEST.STRUCT_TABLE (ID,EMPLOYEE) VALUES ('jsm',ODATA_TEST.type_struct('John Smith', 20090.28));
INSERT INTO ODATA_TEST.STRUCT_TABLE (ID,EMPLOYEE) VALUES ('ddo',ODATA_TEST.type_struct('Diane O''Donnell', 32330.04));

